ls -lh 	Project/NearestSubroutes.py
ls -lh 	Project/main.py
ls -lh 	Project/runlog.txt
ls -lh 	ProjectReport/BigDataHomework.tex
ls -lh 	ProjectReport/images/nn1.jpg
ls -lh 	ProjectReport/images/nn2.jpg
ls -lh 	ProjectReport/images/nn3.jpg
ls -lh 	ProjectReport/images/nn4.jpg
ls -lh 	ProjectReport/images/nn5.jpg
ls -lh 	ProjectReport/images/question2a1example.jpg
ls -lh 	ProjectReport/images/question2a2example.jpg
ls -lh 	ProjectReport/images/questionC1.png
ls -lh 	ProjectReport/images/questionC2.png
ls -lh 	ProjectReport/images/questionC3.png
ls -lh 	ProjectReport/images/questionC4.png
ls -lh 	ProjectReport/images/questionC5.png
ls -lh 	ProjectReport/images/questionCexample.jpg
ls -lh 	ProjectReport/images/subroutes1.jpg
ls -lh 	ProjectReport/images/subroutes2.jpg
ls -lh 	ProjectReport/images/subroutes3.jpg
ls -lh 	ProjectReport/images/subroutes4.jpg
ls -lh 	ProjectReport/images/subroutes5.jpg
